base/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    getRoutes,
    UserViewSet,
    TopicList,
    RoomViewSet,

)


router = DefaultRouter()
router.register(r'rooms', RoomViewSet)
router.register(r'users', UserViewSet)
urlpatterns = [
    path('', getRoutes),
    path('topics/', TopicList.as_view()),
    path('', include(router.urls))
   
]

base/urls.py
from django.urls import path
from .views import (
    home, 
    room, 
    create_room,
    update_room, 
    delete_room,
    login_page,
    logout_page,
    register_page,
    delete_message,
    user_profile,
    update_user,
    topics_page,
    activity_page
)


urlpatterns = [
    path('login/', login_page, name="login"),
    path('register/', register_page, name="register"),
    path('logout/', logout_page, name="logout"),
    path('', home, name="home"),
    path('room/<str:pk>', room, name="room"),
    path('profile/<str:pk>/', user_profile, name="user_profile"),
    path('create-room/', create_room, name='create_room'),
    path('update-room/<str:pk>/', update_room, name='update_room'),
    path('delete-room/<str:pk>/', delete_room, name='delete_room'),
    path('delete-message/<str:pk>/', delete_message, name='delete_message'),
    path('update-user', update_user, name='update_user'),
    path('topics/', topics_page, name='topics'),
    path('activity/', activity_page, name='activity'),
]

studybud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('api/', include('base.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)
    bio = models.TextField(null=True)
    
    avater = models.ImageField(null=True, default="default.svg", upload_to="images")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

class Topic(models.Model):
    name = models.CharField(max_length=200)


    def __str__(self):
        return self.name




class Room(models.Model):
    host = models.ForeignKey(User, related_name='rooms', on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return str(self.name)
    

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-updated', '-created']
    def __str__(self):
        return self.body[0:50]

base/forms.py
from .models import Room, User
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avater', 'name', 'username', 'email', 'bio']
        

base/api/views.py
from rest_framework.decorators import api_view
from rest_framework import generics
from rest_framework import viewsets
from rest_framework.response import Response
from .serializers import (
    UserSerializer,
    TopicSerializer,
    RoomSerializer

)
from base.models import (
    User,
    Topic, 
    Room,
    Message,
)
from rest_framework import permissions
from .permissions import IsOwnerOrReadOnly

@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api/',
        'GET /api/users',
        'GET, CREATE /api/topics',
        'CRUD /api/rooms',
        
    ]
    return Response(routes)



## users
class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


##topics
class TopicList(generics.ListCreateAPIView):
    queryset = Topic.objects.all()
    serializer_class = TopicSerializer


##rooms
class RoomViewSet(viewsets.ModelViewSet):
    queryset = Room.objects.all()
    serializer_class = RoomSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(host=self.request.user)

base/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm

from .models import Room, Topic, Message, User
from .forms import RoomForm, UserForm, MyUserCreationForm
# Create your views here.

# rooms = [
#     {"id": 1, 'name':'Lets learn python'},
#     {"id": 2, 'name':'Lets learn python2'},
#     {"id": 3, 'name':'Lets learn python3'},
#     {"id": 4, 'name':'Lets learn python4'}
# ]



def login_page(request):
    page='login'
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        email = request.POST['email'].lower()
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'invalid credentials')
        
    context = {'page':page}
    return render(request, 'base/login_register.html', context)


def logout_page(request):
    logout(request)
    return redirect('home')


def register_page(request):
    form = MyUserCreationForm()
    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Check Fields To Rectify Your Mistakes')
    context = {'form':form}
    return render(request, 'base/login_register.html', context)


def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    rooms = Room.objects.filter(Q(topic__name__icontains=q) | 
    Q(name__icontains=q) | Q(description__icontains=q)
    )
    room_count = rooms.count()
    topics = Topic.objects.all()[0:5]

    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))

    context = {
        'rooms':rooms,
        'topics':topics,
        'room_count':room_count,
        'room_messages':room_messages
        }
    return render(request, 'base/home.html', context)

def room(request, pk):
    room = Room.objects.get(id=pk)
    room_messages = room.message_set.all()
    participants = room.participants.all()
    if request.method == 'POST':
        message = Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST['body']
        )
        room.participants.add(request.user)
        return redirect('room', pk=room.id)
  
    context = {
        'room': room,
        'room_messages': room_messages,
        'participants':participants
        }
    
    return render(request, 'base/room.html', context)

def user_profile(request, pk):
    user = User.objects.get(id=pk)
    rooms = user.rooms.all()
    room_messages = user.message_set.all()
    topics = Topic.objects.all()
    context = {
        'user':user,
        'rooms':rooms,
        'room_messages': room_messages,
        'topics':topics
    }
    return render(request, 'base/profile.html', context)


@login_required
def create_room(request):
    form = RoomForm()
    topics = Topic.objects.all()
    if request.method =='POST':
        topic_name = request.POST['topic']
        topic, created = Topic.objects.get_or_create(name=topic_name)
        Room.objects.create(
            host=request.user,
            topic = topic,
            name= request.POST['name'],
            description = request.POST['description']

        )
        return redirect('home')


    context = {'form':form, 'topics':topics}
    return render(request, 'base/room_form.html', context)


@login_required
def update_room(request, pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)
    topics = Topic.objects.all()
    if request.user != room.host:
        return HttpResponse('You are not allowed here')


    if request.method == 'POST':
        topic_name = request.POST['topic']
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room.name = request.POST['name']
        room.topic = topic
        room.description = request.POST['description']
        room.save()
        return redirect('home')
    context = {'form':form, 'topics':topics, 'room':room}
    return render(request, 'base/room_form.html', context)

@login_required
def delete_room(request, pk):
    room = Room.objects.get(id=pk)
    if request.user != room.host:
        return HttpResponse('You are not allowed here')

    if request.method == "POST":
        room.delete()
        return redirect('home')
    return render(request, 'base/delete.html', {'obj':room})

@login_required
def delete_message(request, pk):
    message = Message.objects.get(id=pk)
    if request.user != message.user:
        return HttpResponse('You are not allowed here')

    if request.method == "POST":
        message.delete()
        return redirect('home')
    return render(request, 'base/delete.html', {'obj':message})



@login_required
def update_user(request):
    user = request.user
    form = UserForm(instance=user)
    if request.method =='POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('user_profile', pk=user.id)
    context= {
        'form': form
    }
    return render(request, 'base/update-user.html', context)

def topics_page(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    topics = Topic.objects.filter(name__icontains=q)
    context = {'topics':topics}
    return render(request, 'base/topics.html', context)

def activity_page(request):
    room_messages = Message.objects.all()
    context = {'room_messages':room_messages}
    return render(request, 'base/activity.html', context)

base/templates/base/activity.html
{% extends 'main.html' %} {% block content %}
<main class="layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>Recent Activities</h3>
        </div>
      </div>

      <div class="activities-page layout__body">
        {% for message in room_messages %}
        <div class="activities__box">
          <div class="activities__boxHeader roomListRoom__header">
            <a
              href="{% url 'user_profile' message.user.id %}"
              class="roomListRoom__author"
            >
              <div class="avatar avatar--small active">
                <img src="{{message.user.avater.url}}" />
              </div>
              <p>
                @{{message.user}}
                <span>{{message.created|timesince}}</span>
              </p>
            </a>
            {% if request.user == message.user %}
            <div class="roomListRoom__actions">
              <a href="{% url 'delete_message' message.id %}">
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 32 32"
                >
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                  ></path>
                </svg>
              </a>
            </div>
            {% endif %}
          </div>
          <div class="activities__boxContent">
            <p>
              replied to post “<a href="{% url 'room' message.room.id %}">
                {{message.room}}</a
              >”
            </p>
            <div class="activities__boxRoomContent">
              {{ message.body }}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</main>

{% endblock %}

base/templates/base/activity_component.html
<div class="activities">
  <div class="activities__header">
    <h2>Recent Activities</h2>
  </div>
  {% for message in room_messages %}
  <div class="activities__box">
    <div class="activities__boxHeader roomListRoom__header">
      <a
        href="{% url 'user_profile' message.user.id %}"
        class="roomListRoom__author"
      >
        <div class="avatar avatar--small active">
          <img src="{{message.user.avater.url}}" />
        </div>
        <p>
          @{{message.user}}
          <span>{{message.created|timesince}}</span>
        </p>
      </a>
      {% if request.user == message.user %}
      <div class="roomListRoom__actions">
        <a href="{% url 'delete_message' message.id %}">
          <svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            viewBox="0 0 32 32"
          >
            <title>remove</title>
            <path
              d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
            ></path>
          </svg>
        </a>
      </div>
      {% endif %}
    </div>
    <div class="activities__boxContent">
      <p>
        replied to post “<a href="{% url 'room' message.room.id %}">
          {{message.room}}</a
        >”
      </p>
      <div class="activities__boxRoomContent">
        {{ message.body }}
      </div>
    </div>
  </div>
  {% endfor %}
</div>

base/templates/base/delete.html
{% extends 'main.html' %} {% block content %}
<main class="delete-item layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{{request.META.HTTP_REFERER}}">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>Back</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" method="POST" action="">
          {% csrf_token %}
          <div class="form__group">
            <p>Are you sure you want to delete "{{obj}}"?</p>
          </div>

          <div class="for__group">
            <input class="btn btn--main" type="submit" value="Confirm" />
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}

base/templates/base/feed_component.html
{% for room in rooms %}
<div class="roomListRoom">
  <div class="roomListRoom__header">
    <a
      href="{% url 'user_profile' room.host.id %}"
      class="roomListRoom__author"
    >
      <div class="avatar avatar--small">
        <img src="{{room.host.avater.url}}" />
      </div>
      <span>@{{room.host.username}}</span>
    </a>
    <div class="roomListRoom__actions">
      <span>{{ room.created|timesince}} ago</span>
    </div>
  </div>
  <div class="roomListRoom__content">
    <a href="{% url 'room' room.id %}">{{ room.name }}</a>
  </div>
  <div class="roomListRoom__meta">
    <a href="{% url 'room' room.id %}" class="roomListRoom__joined">
      <svg
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        width="32"
        height="32"
        viewBox="0 0 32 32"
      >
        <title>user-group</title>
        <path
          d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
        ></path>
        <path
          d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
        ></path>
        <path
          d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
        ></path>
        <path
          d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
        ></path>
      </svg>
      {{room.participants.all.count}} Joined
    </a>
    <p class="roomListRoom__topic">{{room.name}}</p>
  </div>
</div>
{% endfor %}

base/templates/base/home.html
{% extends 'main.html' %} {% block content %}
<main class="layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include 'base/topic_component.html' %}

    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="mobile-menu">
        <form action="{% url 'home' %}" class="header__search">
          <label>
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input name="q" placeholder="Search for posts" />
          </label>
        </form>
        <div class="mobile-menuItems">
          <a class="btn btn--main btn--pill" href="{% url 'topics' %}"
            >Browse Topics</a
          >
          <a class="btn btn--main btn--pill" href="{% url 'activity' %}"
            >Recent Activities</a
          >
        </div>
      </div>
      <div class="roomList__header">
        <div>
          <h2>Trading Room</h2>
          <p>{{ room_count }} Rooms avaliable</p>
        </div>
        <a class="btn btn--main" href="{% url 'create_room' %}">
          <svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            viewBox="0 0 32 32"
          >
            <title>add</title>
            <path
              d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
            ></path>
          </svg>
          Create Room
        </a>
      </div>
      {% include 'base/feed_component.html' %}
    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'base/activity_component.html' %}
 
    <!-- Activities End -->
  </div>
</main>
{% endblock %}

base/templates/base/login_register.html
{% extends 'main.html' %} {% block content %}
<main class="auth layout">
   {% if page == 'login'%}
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Login</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Find your Trading partner</h2>
        {% if messages %} {% for message in messages %}
        <p class="auth__tagline">{{message}}</p>
        {% endfor%} {% endif %}
        <form class="form" action="" method="POST">
          {% csrf_token %}
          <div class="form__group form__group">
            <label for="room_name">Email</label>
            <input
              id="username"
              name="email"
              type="text"
              placeholder="e.g. dennis_ivy"
            />
          </div>
          <div class="form__group">
            <label for="password">Password</label>
            <input
              id="password"
              name="password"
              type="password"
              placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
            />
          </div>

          <button class="btn btn--main" type="submit">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
              ></path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
              ></path>
            </svg>

            Login
          </button>
        </form>

        <div class="auth__action">
          <p>Haven't signed up yet?</p>
          <a href="{% url 'register' %}" class="btn btn--link">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Register</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Find your Trading partners</h2>
        {% if messages %} {% for message in messages %}
        <p class="auth__tagline">{{message}}</p>
        {% endfor%} {% endif %}
        <form class="form" action="" method="POST">
          {% csrf_token %} {% for field in form %}
          <div class="form__group form__group">
            <label for="room_name">{{field.label}}</label>
            {{field.errors}} {{field }}
          </div>
          {% endfor %}

          <button class="btn btn--main" type="submit">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
              ></path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
              ></path>
            </svg>

            Register
          </button>
        </form>

        <div class="auth__action">
          <p>Already signed up?</p>
          <a href="{% url 'login' %}" class="btn btn--link">Login</a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</main>
{% endblock %}

base/templates/base/profile.html
{% extends 'main.html' %} {% block content %}
<main class="profile-page layout layout--3">
  <div class="container">
    <!-- Topics Start -->

    {% include 'base/topic_component.html' %}
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="profile">
        <div class="profile__avatar">
          <div class="avatar avatar--large active">
            <img src="{{user.avater.url}}" />
          </div>
        </div>
        <div class="profile__info">
          <h3>{{user.username}}</h3>
          <p>{{user.username}}</p>
          {% if request.user == user %}
          <a href="{% url 'update_user' %}" class="btn btn--main btn--pill"
            >Edit Profile</a
          >
          {% endif %}
        </div>
        <div class="profile__about">
          <h3>About</h3>
          <p>
            {{ user.bio}}
          </p>
        </div>
      </div>

      <div class="roomList__header">
        <div>
          <h2>Study Rooms Hosted by <span>@{{ user.username}}</span></h2>
        </div>
      </div>
      {% include 'base/feed_component.html' %}s
    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'base/activity_component.html' %}
    <!-- Activities End -->
  </div>
</main>
{% endblock %}

base/templates/base/topic_component.html
<div class="topics">
  <div class="topics__header">
    <h2>Browse Topics</h2>
  </div>
  <ul class="topics__list">
    <li>
      <a href="{% url 'home' %}" class="active"
        >All <span>{{topics.count}}</span></a
      >
    </li>

    {% for topic in topics %}
    <li>
      <a href="{% url 'home' %}?q={{topic.name}}"
        >{{topic.name}}<span>{{topic.room_set.all.count}}</span></a
      >
    </li>
    {% endfor %}
  </ul>
  <a class="btn btn--link" href="{% url 'topics' %}">
    More
    <svg
      version="1.1"
      xmlns="http://www.w3.org/2000/svg"
      width="32"
      height="32"
      viewBox="0 0 32 32"
    >
      <title>chevron-down</title>
      <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
    </svg>
  </a>
</div>

base/templates/base/topics.html
{% extends 'main.html' %} {% block content %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>Browse Topics</h3>
        </div>
      </div>

      <div class="topics-page layout__body">
        <form action="" method="GET" class="header__search">
          <label>
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input name="q" placeholder="Search for topics" />
          </label>
        </form>

        <ul class="topics__list">
          <li>
            <a href="{% url 'topics' %}" class="active"
              >All <span>{{topics.count}}</span></a
            >
          </li>
          {% for topic in topics %}
          <li>
            <a href="{% url 'home' %}?q={{topic.name}}"
              >{{topic.name}}<span>{{ topic.room_set.all.count }}</span></a
            >
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</main>
{% endblock %}